"""Constants for the XRemote JSON protocol (reverse-engineered from
AniLabX/XRemoteDesktop's XRemoteServer/XRemoteData/XRemoteResponseData).

We deliberately do not model the full schema as typed classes - the node only
needs to read/patch a handful of known keys and pass everything else through
untouched, so plain dicts are enough.
"""

API_VERSION = 10

# XRemoteData.COMMAND values
CMD_PING = "PING"
CMD_HEARTBEAT = "HEARTBEAT"
CMD_GET_PLAY_INFO = "GET_PLAY_INFO"
CMD_PLAY_VIDEO = "PLAY_VIDEO"
CMD_CLOSE_PLAYER = "CLOSE_PLAYER"
CMD_UPDATE_STATE = "UPDATE_STATE"

# XRemoteData.PLAY_COMMAND values
PLAY_CMD_NONE = "NONE"
PLAY_CMD_PLAY = "PLAY"
PLAY_CMD_MUTE = "MUTE"
PLAY_CMD_SEEK_TO = "SEEK_TO"
PLAY_CMD_SEEK_BY = "SEEK_BY"
PLAY_CMD_VOLUME_UP = "VOLUME_UP"
PLAY_CMD_VOLUME_DOWN = "VOLUME_DOWN"

SEEK_COMMANDS = {PLAY_CMD_SEEK_TO, PLAY_CMD_SEEK_BY}

# XRemoteResponseData.RESPONSE values
RESP_ALIVE = "ALIVE"
RESP_COMMAND_SUCCESS = "COMMAND_SUCCESS"
RESP_COMMAND_FAIL = "COMMAND_FAIL"
RESP_PLAYER_NOT_RUNNING = "PLAYER_NOT_RUNNING"
RESP_VERSION_INCOMPATIBLE = "VERSION_INCOMPATIBLE"
RESP_EXCEPTION = "EXCEPTION"

# Top-level XRemoteData keys
KEY_API_VERSION = "API_VERSION"
KEY_CLIENT_NAME = "CLIENT_NAME"
KEY_CLIENT_APP_NAME = "CLIENT_APP_NAME"
KEY_CLIENT_APP_VERSION = "CLIENT_APP_VERSION"
KEY_CLIENT_TYPE = "CLIENT_TYPE"
KEY_COMMAND = "COMMAND"
KEY_PLAY_COMMAND = "PLAY_COMMAND"
KEY_PLAY_INFO = "PLAY_INFO"
KEY_PLAY_DATA = "PLAY_DATA"

# XRemotePlayData keys
KEY_SERVICE_ID = "SERVICE_ID"
KEY_CONTENT_ID = "CONTENT_ID"
KEY_CONTENT_TITLE = "CONTENT_TITLE"
KEY_CONTENT_SUBTITLE = "CONTENT_SUBTITLE"
KEY_SEASON = "SEASON"
KEY_TRANSLATION = "TRANSLATION"
KEY_EPISODE = "EPISODE"
KEY_LINK_ITEM = "LINK_ITEM"
KEY_PARSE_LINK = "PARSE_LINK"
KEY_POSITION = "POSITION"
KEY_WINDOW = "WINDOW"

# LinkItem keys
KEY_LINK_NAME = "NAME"
KEY_LINK_PARTS = "LINK_PARTS"
KEY_IS_ALTERNATIVE = "IS_ALTERNATIVE"

# ParseLink keys
KEY_ORIGINAL = "ORIGINAL"
KEY_DIRECT = "DIRECT"
KEY_HEADERS_FOR_DIRECT = "HEADERS_FOR_DIRECT"
KEY_HEADERS_FOR_ORIGINAL = "HEADERS_FOR_ORIGINAL"

# XRemoteResponseData keys
KEY_RESPONSE = "RESPONSE"
KEY_PLAY_NFO = "PLAY_NFO"  # sic - typo present in the real protocol

# XRemotePlayInfo keys (inside PLAY_NFO)
KEY_NFO_POSITION = "POSITION"
KEY_NFO_DURATION = "DURATION"

# Fixed User-Agent the real receiver hardcodes for playback (Constants.USER_AGENT)
RECEIVER_USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
)
